services:
  - type: web
    name: weather-web-app # Tên ứng dụng của bạn
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false # Chúng ta sẽ đặt key này trên web Render
